### PR TITLE
renamed rvc, rvd to cryptode, cryptoded

### PR DESCRIPTION
**Pull request by jjr840430**

### CODE REVIEW

**Comment by jjr840430** [comment]
@ronaldtse there was some bug related to certificate expiration.
I will replace the certificates with new ones.

**Comment by jjr840430** [comment]
@ronaldtse Fixed!

**Comment by ronaldtse** [comment]
@jjr840430 for the certificates, are they configured with a long expiration period? Or are they very short such that they get expired soon? We should use a long period since it is only for testing. Thanks!

**Comment by jjr840430** [comment]
@ronaldtse the certificate will be expired in `Dec  1 15:57:56 2021 GMT`.
I will try to extend it with long period.

**Comment by ronaldtse** [comment]
Thanks, alternatively, it's easier to generate a new certificate pair during CI (if it doesn't take too long)?

**Comment by jjr840430** [comment]
@ronaldtse it doesn't take too long. I will try to find the way to generate certificates during CI.

**Pull request merged**
